# Generated by Django 5.1.6 on 2025-03-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ownerprofile_aaaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='aaaa',
        ),
    ]
