# Generated by Django 5.1.6 on 2025-03-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_residence_alter_property_owner_property_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='residence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.residence'),
            preserve_default=False,
        ),
    ]
